# Generated by Django 3.2.4 on 2021-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210613_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='titulo',
            field=models.CharField(default='carrito', max_length=255, null=True),
        ),
    ]
