# Generated by Django 3.2.4 on 2021-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210613_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_alta',
            field=models.DateTimeField(null=True),
        ),
    ]
