# Generated by Django 3.2.4 on 2021-06-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_carrito_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_creacion',
        ),
    ]
