# Generated by Django 3.2.4 on 2021-06-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_carrito_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(through='main.ItemCarrito', to='main.Producto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carrito'),
        ),
    ]
