# Generated by Django 3.2.4 on 2021-06-23 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_auto_20210623_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ('-fecha_Alta',)},
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='created',
            new_name='fecha_Alta',
        ),
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='price',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='address',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='city',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='quantity',
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
