# Generated by Django 3.2.4 on 2021-06-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210623_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='quantity',
            new_name='cantidad',
        ),
    ]
